version: "3.9"

services:
  backend:
    build:
      context: ./backend
    restart: always
    depends_on:
      - db
    env_file:
      - .env
  db:
    image: postgres:16
    restart: always
    env_file:
      - .env
    volumes:
      - postgres-data:/var/lib/postgresql/data
  migrate:
    image: migrate/migrate:v4.16.2
    volumes:
      - ./backend/migrations:/migrations
  administradores:
    build:
      context: ./administradores
    depends_on:
      - backend
    restart: always
    environment:
      - ORIGIN=${ORIGIN_ADMINISTRADORES}
    env_file:
      - .env
    ports:
      - ${PORT_ADMINISTRADORES}:3000
  empresas:
    build:
      context: ./empresas
    depends_on:
      - backend
    restart: always
    environment:
      - ORIGIN=${ORIGIN_EMPRESAS}
    env_file:
      - .env
    ports:
      - ${PORT_EMPRESAS}:3000

volumes:
  postgres-data:
