version: "3.9"

services:
  backend:
    image: cosmtrek/air:v1.49.0
    working_dir: /app
    env_file:
      - .env
    ports:
      - ${PORT_BACKEND}:3000
    volumes:
      - ./backend:/app
    entrypoint:
      [
        "/go/bin/air",
        "--build.cmd",
        "go build -buildvcs=false -o ./tmp/main ."
      ]
  db:
    image: postgres:16
    env_file:
      - .env
    volumes:
      - postgres-data:/var/lib/postgresql/data
  migrate:
    image: migrate/migrate:v4.16.2
    volumes:
      - ./backend/migrations:/migrations
  administradores:
    build:
      context: ./administradores
    env_file:
      - .env
    ports:
      - ${PORT_ADMINISTRADORES}:5173
    volumes:
      - ./administradores:/app
    command: [ "npm", "run", "dev", "--", "--host" ]
  empresas:
    build:
      context: ./empresas
    env_file:
      - .env
    ports:
      - ${PORT_EMPRESAS}:5173
    volumes:
      - ./empresas:/app
    command: [ "npm", "run", "dev", "--", "--host" ]

volumes:
  postgres-data:
